### ISSUE TITLE
Fixed dont showing notifications

### ISSUE THREAD

**Issue by kenlallemand** [gigitux/youpforwhatsapp#14]
actually i am using ubuntu 20.04 with vainilla gnome 3.36 and the notifications dont show, the permission request its shown but when comes the time for accept it, dont appear the request on the screen

**Comment by gigitux** [comment]
It is right that no notification confirmation pop-ups appear.
Are you sure they don't work?

**Comment by kenlallemand** [comment]
the app ask me everytime i launch it for the permission, how i disable this? its annoying

**Comment by gigitux** [comment]
Fixed

**Comment by ghost** [comment]
Tnkx, ill test it on fedora.
