### ISSUE TITLE
icon is wrong in Qt based desktops

### ISSUE THREAD

**Issue by damianatorrpm** [gigitux/youpforwhatsapp#18]
The .svg file used by the desktop file can't be displayed in Qt based desktop environments:
https://bugreports.qt.io/browse/QTBUG-85551

It uses a feature of .svg that Qt won't support (only SVG Basic and SVG Tiny are supported).
This results the icon being wrong in lxqt (tested) and probably KDE and deepin as well.

I suggest to use a .png or use an .svg that uses SVG Basic.

**Comment by gigitux** [comment]
Fixed! Now youp uses a png logo
