### ISSUE TITLE
Feature request: Hide in systray

### ISSUE THREAD

**Issue by jeroenpraat** [gigitux/youpforwhatsapp#25]
Please add an option to hide the application window in the systray, like other IM apps?

I know that in Gnome shell you need an extension for that and there also other display managers that have a systray. I personally use Gnome shell with an extension for the systray. Removing the systray is the biggest error Gnome made. :-(

**Comment by gigitux** [comment]
Thanks for opening the issue!
Yes, it is a really important improvement! I'll work on it!

**Comment by Slomo17** [comment]
Could you please make it optional, i like it the way it is.

**Comment by andreluisos** [comment]
Any news on it?

**Comment by gigitux** [comment]
I'm working on it :)

**Comment by gigitux** [comment]
Solved
