### ISSUE TITLE
Find a better name for gtkWhats

### ISSUE THREAD

**Issue by gigitux** [gigitux/youpforwhatsapp#3]
Is GtkWhats a clear and cute name for this app?

**Comment by ZanderBrown** [comment]
Not really

**Comment by gigitux** [comment]
@ZanderBrown Any ideas?

**Comment by bertob** [comment]
It would be good to avoid including parts of the Whatsapp name to avoid potential trademark issues (similar to the icon issue mentioned in #4).

As for suggestions, personally I'd find it funny to lean into the shitty dad joke that is the original app's name and do someting like "Not Much". Alternatively you could also do something fairly random and add "for Whatsapp" to the name in app stores, like e.g. "Girens for Plex" does.

**Comment by gigitux** [comment]
@bertob 

Thanks for your advice! I will take them into consideration 🙏

**Comment by jgarciao** [comment]
Here are some examples for similar apps in the Apple Store: https://www.apple.com/es/search/whatsapp?src=serp

For me (English is not my mother language) WhatsApp reminds the [Budweiser commercial](https://www.youtube.com/watch?v=xkqKzqyvebg), so maybe Whassup, Wassuup, Wazzup or even WhosThere could be a possible name for this app

Install WhosThere for WhatsApp at Flathub!

More info at:

- https://en.wikipedia.org/wiki/Whassup%3F
- https://www.urbandictionary.com/define.php?term=wazzup

**Comment by arvigeus** [comment]
Another stupid suggestion: Ceiling
- What's up?
- The ceiling!

**Comment by jeroenpraat** [comment]
Ghats

**Comment by gigitux** [comment]
The new name will be "youp for whatsapp"

**Comment by jeroenpraat** [comment]
Youp?

**Comment by gigitux** [comment]
Yes, youp!

In the next days I will release a new version with a lot of bugfix
