### ISSUE TITLE
Create a valid logo for gtkwhats

### ISSUE THREAD

**Issue by gigitux** [gigitux/youpforwhatsapp#4]
It would be great to have a dedicated gtkwhats logo

**Comment by pedrofleck** [comment]
Is it really necessary? Since this is just a wrapper. Maybe the regular WhatsApp logo would be more familiar to new users.

**Comment by gigitux** [comment]
@pedrofleck I understand your point of view, but I think it is better to use a custom logo so as not to have copyright problems

**Comment by gigitux** [comment]
fixed
