### ISSUE TITLE
cannot access downloaded files

### ISSUE THREAD

**Issue by hferreiro** [gigitux/youpforwhatsapp#40]
I guess they are stored inside the flatpak container instead of the user's Download folder.

**Comment by gigitux** [comment]
Mmm, what version are you using?

**Comment by hferreiro** [comment]
The one from flathub.

**Comment by gigitux** [comment]
Are you sure? I have tried and seems that works fine

**Comment by hferreiro** [comment]
It's working now, I guess it was fixed at some point.
