### ISSUE TITLE
No connection to Whatsapp

### ISSUE THREAD

**Issue by cliffordsnow** [gigitux/youpforwhatsapp#43]
I'm running youp 2.0 flatpak on Fedora 33. It worked fine until now when youp just shows the title bar with an about and settings button and a light/dark mode switch but no way to connect to Whatsapp. 

I tried logging out from all devices on my phone but that didn't solve the problem.

**Comment by gigitux** [comment]
Did you try to kill youp with kill command?

**Comment by cliffordsnow** [comment]
I finally killed the application and removed then reinstalled it manually and now it can connect to Whatsapp. Thanks for the suggestion.

**Comment by gigitux** [comment]
No problem 👍
