### ISSUE TITLE
gtkwhats using 4-6% cpu constantly

### ISSUE THREAD

**Issue by Sirtz** [gigitux/youpforwhatsapp#9]
Hi,

first of all thank you so much for creating this, have been looking for a while for something similar.
Looking at gnome system monitor I see gtkwhats constantly taking up 4% cpu, sometimes more. This is a bit of a problem on a laptop.
I am on fedora 32 gnome wayland, on a intel core i7-7500U.
If you need logs let me know.

**Comment by gigitux** [comment]
@Sirtz 
Can you send me some logs?
I can't replicate it

![monitor](https://user-images.githubusercontent.com/4463174/84934109-2b5a0b00-b0d7-11ea-849a-6dd60d2b1c56.png)

**Comment by Sirtz** [comment]
`flatpak run com.gigitux.gtkwhats
Gtk-Message: 12:28:58.198: Failed to load module "pk-gtk-module"
Gtk-Message: 12:28:58.199: Failed to load module "pk-gtk-module"

** (gtkwhats:2): WARNING **: 12:28:58.297: AT-SPI: Could not obtain desktop path or name


** (gtkwhats:2): WARNING **: 12:28:58.302: atk-bridge: GetRegisteredEvents returned message with unknown signature

** (gtkwhats:2): WARNING **: 12:28:58.302: atk-bridge: get_device_events_reply: unknown signature

** (gtkwhats:2): WARNING **: 12:28:58.302: atk-bridge: get_device_events_reply: unknown signature
Gtk-Message: 12:28:58.320: Failed to load module "pk-gtk-module"
Gtk-Message: 12:28:58.329: Failed to load module "pk-gtk-module"

** (WebKitWebProcess:9): WARNING **: 12:28:58.395: AT-SPI: Could not obtain desktop path or name


** (WebKitWebProcess:9): WARNING **: 12:28:58.400: atk-bridge: GetRegisteredEvents returned message with unknown signature

** (WebKitWebProcess:9): WARNING **: 12:28:58.400: atk-bridge: get_device_events_reply: unknown signature

** (WebKitWebProcess:9): WARNING **: 12:28:58.400: atk-bridge: get_device_events_reply: unknown signature
`
Running in terminal gives me this, what else do you need?

Monitor
![Screenshot from 2020-06-20 12-31-03](https://user-images.githubusercontent.com/26656736/85198528-fe357480-b2f1-11ea-939f-5c1ae8ecb069.png)

Powertop
![Screenshot from 2020-06-20 12-32-28](https://user-images.githubusercontent.com/26656736/85198559-29b85f00-b2f2-11ea-80f8-1aa12f8d2541.png)

**Comment by gigitux** [comment]
@Sirtz 
It is really strange as a problem.

I can't reproduce it :(

I'm not very flatpak expert, but with:

```
flatpak run com.gigitux.gtkwhats
```

I don't see any logs :(

![immagine](https://user-images.githubusercontent.com/4463174/85205324-0e157e80-b31b-11ea-9b2d-c86e73c23caf.png)

**Comment by gigitux** [comment]
I can't reproduce it
